import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by home',
}
export default function Home() {
  return (
    <div className="bg-white py-6 sm:py-8 lg:py-12">
      <div className="mx-auto max-w-screen-xl px-4 md:px-8">
        <div className="mb-10 md:mb-16">
          <h1 className='mb-4 text-3xl font-bold text-gray-800 md:mb-6 lg:text-3xl'>Welcome to WEB - ABC - Home</h1>
        </div>
      </div>
    </div>
  )
}
